@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNta2VrM2J3aTAwMDFvOGk4cDU0aXAzcHEiLCJlbWFpbCI6ImFkbWludEB0ZXN0LmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2ODQ4NzYzNywiZXhwIjoxNzY4NDk4NDM3fQ.neCMNHTtl6qgc1kTHa1UsgqioxMtAA9j7xDaQYt4dH0

POST {{baseUrl}}/formations
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Formation Développement Web",
  "description": "Formation complète backend & frontend",
  "categories": [
    "cmkekx0nj0000oki8rt33k1q7"
  ]
}

### get all formation / module
GET {{baseUrl}}/formations
Authorization: Bearer {{token}}

### get formation by id
GET {{baseUrl}}/formations/cmkfk06jt0003vci8wcvpxz04
Authorization: Bearer {{token}}

### update formation
PUT {{baseUrl}}/formations/cmkfk06jt0003vci8wcvpxz04
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Formation Web Avancée",
  "description": "Node.js, Prisma, React"
}

### error test
POST {{baseUrl}}/formations
Content-Type: application/json

{
    "title": "HDF",  
    "description": "FSD", 
    "categories": 3
}

### get all formation
GET http://localhost:3000/formations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNta2VrM2J3aTAwMDFvOGk4cDU0aXAzcHEiLCJlbWFpbCI6ImFkbWludEB0ZXN0LmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2ODQyODc2OCwiZXhwIjoxNzY4NDM5NTY4fQ.5rmQ9S4nF6oGPl4vWhS9t99oksfUrPz9_evV4z-O9B0

### get formation by id
GET http://localhost:3000/formations/cmkekx0nj0000oki8rt33k1q7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNta2VrM2J3aTAwMDFvOGk4cDU0aXAzcHEiLCJlbWFpbCI6ImFkbWludEB0ZXN0LmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2ODQyODc2OCwiZXhwIjoxNzY4NDM5NTY4fQ.5rmQ9S4nF6oGPl4vWhS9t99oksfUrPz9_evV4z-O9B0

### update formation by an admin 
POST http://localhost:3000/formations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNta2VrM2J3aTAwMDFvOGk4cDU0aXAzcHEiLCJlbWFpbCI6ImFkbWludEB0ZXN0LmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2ODQyODc2OCwiZXhwIjoxNzY4NDM5NTY4fQ.5rmQ9S4nF6oGPl4vWhS9t99oksfUrPz9_evV4z-O9B0
Content-Type: application/json

{
  "name": "Nouvelle catégorie"
}

### delete formation by admin : HTTP/1.1 200 OK
DELETE http://localhost:3000/formations/cmkekz74n0003oki8c29ps2e3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNta2VrM2J3aTAwMDFvOGk4cDU0aXAzcHEiLCJlbWFpbCI6ImFkbWludEB0ZXN0LmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2ODQyODc2OCwiZXhwIjoxNzY4NDM5NTY4fQ.5rmQ9S4nF6oGPl4vWhS9t99oksfUrPz9_evV4z-O9B0
