@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNta2ZrOHYzZjAwMDZ2Y2k4cG9sYnh5eTEiLCJlbWFpbCI6InByb2ZAdGVzdC5jb20iLCJyb2xlIjoiZW5zZWlnbmFudCIsImlhdCI6MTc2ODQ4ODI4MCwiZXhwIjoxNzY4NDk5MDgwfQ.eV4w0FmgKIRj368UkNTdRRHHADNsW-WpJzpBu0eZip4

### sign up / create user admin 
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "prof",
  "lastName": "prof",
  "email": "prof@test.com",
  "password": "password123",
  "role": "enseignant"
}
### HTTP/1.1 200 OK
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "prof@test.com",
  "password": "password123"
}

### "message": "Leçon créée avec succès."
POST {{baseUrl}}/lecons
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Introduction à Node.js",
  "description": "Présentation du runtime Node.js",
  "body": "Node.js permet d’exécuter JavaScript côté serveur.",
  "coursId": "cmkfk0ncw0004vci8sshrzc4a",
  "quizId": null
}

### get all lecons
GET {{baseUrl}}/lecons
Authorization: Bearer {{token}}

### get lecon par id
GET {{baseUrl}}/lecons/cmkfkaes60007vci8cemnxs9d
Authorization: Bearer {{token}}


### update lecon
PUT {{baseUrl}}/lecons/cmkfkaes60007vci8cemnxs9d
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Node.js Avancé",
  "description": "Event loop, streams",
  "body": "Approfondissement du fonctionnement interne de Node.js",
  "coursId": "cmkfk0ncw0004vci8sshrzc4a",
  "quizId": null
}

### delete a lecon

DELETE {{baseUrl}}/lecons/cmkfkdz4d0008vci8e9v4xkwu
Authorization: Bearer {{token}}
