### POST formation
POST http://localhost:3000/lecon
Content-Type: application/json

{
    "text": "HDasdF sjsaid ffkskd fkfkwk",  
    "quizID": 2355
}

### get all question 
GET http://localhost:3000/question
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNta2VrM2J3aTAwMDFvOGk4cDU0aXAzcHEiLCJlbWFpbCI6ImFkbWludEB0ZXN0LmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2ODQyODc2OCwiZXhwIjoxNzY4NDM5NTY4fQ.5rmQ9S4nF6oGPl4vWhS9t99oksfUrPz9_evV4z-O9B0

### update question by an admin 
POST http://localhost:3000/question
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNta2VrM2J3aTAwMDFvOGk4cDU0aXAzcHEiLCJlbWFpbCI6ImFkbWludEB0ZXN0LmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2ODQyODc2OCwiZXhwIjoxNzY4NDM5NTY4fQ.5rmQ9S4nF6oGPl4vWhS9t99oksfUrPz9_evV4z-O9B0
Content-Type: application/json

{
  "name": "Nouvelle catégorie"
}

### delete question by admin : HTTP/1.1 200 OK
DELETE http://localhost:3000/question/cmkekz74n0003oki8c29ps2e3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNta2VrM2J3aTAwMDFvOGk4cDU0aXAzcHEiLCJlbWFpbCI6ImFkbWludEB0ZXN0LmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2ODQyODc2OCwiZXhwIjoxNzY4NDM5NTY4fQ.5rmQ9S4nF6oGPl4vWhS9t99oksfUrPz9_evV4z-O9B0
