### sign in / create user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Student",
  "email": "alic4@student.com",
  "password": "password123",
  "role": "etudiant"
}

### log in 
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "alic4@student.com",
  "password": "password123"
}
